# Generated by Django 3.1.2 on 2020-11-06 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_title', models.CharField(default='例：抖音-记录美好生活', max_length=50)),
                ('app_intro', models.TextField(default='APP介绍')),
                ('app_url', models.CharField(default='HTTP://', max_length=100)),
                ('app_icon', models.ImageField(default='default_icon.png', upload_to='images/')),
                ('app_image', models.ImageField(default='default_image.png', upload_to='images/')),
                ('votes', models.IntegerField(default=1)),
                ('pub_date', models.DateField()),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
